# Sulaiman's Numpy Practice

## Part 1

### 1.

In [11]:
import numpy as np

arr1d = np.arange(1, 11)
print(arr1d)

[ 1  2  3  4  5  6  7  8  9 10]


### 2.

In [3]:
arr2d = np.ones((3, 3))
print(arr2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 3.

In [4]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.12652432 0.08368838 0.86213628]
 [0.01307766 0.19861412 0.99594263]
 [0.26043157 0.22839793 0.55534169]]


### 4.

In [6]:
even_numbers = np.arange(10, 51, 2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


### 5.

In [7]:
linspace_array = np.linspace(0, 1, 7)
print(linspace_array)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


### 6.

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape = arr.shape
print(shape)
ndim = arr.ndim
print(ndim)
dtype = arr.dtype
print(dtype)

(2, 3)
2
int64


## Part 2

### 1.

In [13]:
reshaped_arr = arr1d.reshape(2, 5)
print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 2.

In [14]:
reshaped_arr.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

### 3.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_arr = np.stack((a, b), axis=1)
print(stacked_arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

### 4.

In [21]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
matrix_stack = np.vstack((m1, m2))
print(matrix_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 5.

In [24]:
arr_to_split = np.arange(16).reshape(4, 4)
print(arr_to_split)
hsplit_arrays = np.hsplit(arr_to_split, 2)
for split_arrays in hsplit_arrays:
    print(split_arrays)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### 6.

In [36]:
vsplit_arrays_in_index_2 = np.split(arr_to_split, [2], axis = 0)
for split_arrays in vsplit_arrays_in_index_2:
    print(split_arrays)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


## Part 3

### 1.

In [40]:
data = np.array([[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]])
print(data[0,1])

11


### 2.

In [42]:
print(data[0:2, :])

[[10 11 12]
 [13 14 15]]


### 3.

In [46]:
rows = np.array([0, 1, 2])
columns = np.array([1, 2, 1])
print(data[rows, columns])

[11 15 17]


### 4.

In [48]:
scores = np.array([85, 92, 78, 65, 95, 88])
condition = scores > 80
filtered_scores = scores[condition]
print(filtered_scores)

[85 92 95 88]


## Part 4

### 1.

In [49]:
arr_op1 = np.array([10, 20, 30]) 
arr_op2 = np.array([2, 4, 6])
arr_div = arr_op1 / arr_op2
print(arr_div)

[5. 5. 5.]


### 2.

In [50]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum_of_elements = np.sum(matrix)
print(sum_of_elements)

45


### 3.

In [53]:
print(matrix.mean())

5.0


### 4.

In [54]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
print(discounted_prices)

[ 90. 135. 180. 225.]
