# Smart Building

## 1.

In [64]:
import numpy as np

time_in_minutes = np.arange(0, 1440)
print(time_in_minutes)

[   0    1    2 ... 1437 1438 1439]


In [65]:
temperature_data = np.random.normal(loc=22, scale=5, size=1440)
print(temperature_data)

[27.44817873 28.79061616 14.39284048 ... 30.95336364 19.91773981
 17.51194075]


In [66]:
humidity_data = np.random.normal(loc=55, scale=15, size=1440)
print(humidity_data)

[60.47384268 53.63595184 57.5874363  ... 62.69716125 48.26328925
 78.75192813]


In [67]:
pressure_data = np.random.normal(loc=1012, scale=10, size=1440)
print(pressure_data)

[1016.59045756 1016.77150153 1005.97335218 ... 1013.47865955  999.55506663
 1017.60254771]


In [68]:
home_data = np.concatenate((time_in_minutes.reshape(-1, 1),
                            temperature_data.reshape(-1, 1),
                            humidity_data.reshape(-1, 1),
                            pressure_data.reshape(-1, 1)), axis=1)
print(home_data)

[[0.00000000e+00 2.74481787e+01 6.04738427e+01 1.01659046e+03]
 [1.00000000e+00 2.87906162e+01 5.36359518e+01 1.01677150e+03]
 [2.00000000e+00 1.43928405e+01 5.75874363e+01 1.00597335e+03]
 ...
 [1.43700000e+03 3.09533636e+01 6.26971613e+01 1.01347866e+03]
 [1.43800000e+03 1.99177398e+01 4.82632893e+01 9.99555067e+02]
 [1.43900000e+03 1.75119407e+01 7.87519281e+01 1.01760255e+03]]


## 2.

In [69]:
average_temperature = home_data[:, 1].mean()
print(f"Average Temperature: {average_temperature}")
average_humidity = home_data[:, 2].mean()
print(f"Average Humidity: {average_humidity}")
average_pressure = home_data[:, 3].mean()
print(f"Average Pressure: {average_pressure}")

max_temperature = home_data[:, 1].max()
print(f"Max Temperature: {max_temperature}")
min_temperature = home_data[:, 1].min()
print(f"Min Temperature: {min_temperature}")
max_humidity = home_data[:, 2].max()
print(f"Max Humidity: {max_humidity}")
min_humidity = home_data[:, 2].min()
print(f"Min Humidity: {min_humidity}")
max_pressure = home_data[:, 3].max()
print(f"Max Pressure: {max_pressure}")
min_pressure = home_data[:, 3].min()
print(f"Min Pressure: {min_pressure}")


Average Temperature: 22.13665137783482
Average Humidity: 55.19635439846863
Average Pressure: 1012.2974582890321
Max Temperature: 37.78476144207338
Min Temperature: 3.236576388647112
Max Humidity: 100.88811333702049
Min Humidity: 12.241129902626014
Max Pressure: 1046.7007261485894
Min Pressure: 983.7251647897236


In [70]:
std_average_temperature = home_data[:, 1].std()
print(f"Standard Deviation of Average Temperature: {std_average_temperature}")
std_average_humidity = home_data[:, 2].std()
print(f"Standard Deviation of Average Humidity: {std_average_humidity}")
std_average_pressure = home_data[:, 3].std()
print(f"Standard Deviation of Average Pressure: {std_average_pressure}")

std_max_temperature = home_data[:, 1].std()
print(f"Standard Deviation of Max Temperature: {std_max_temperature}")
std_min_temperature = home_data[:, 1].std()
print(f"Standard Deviation of Min Temperature: {std_min_temperature}")
std_max_humidity = home_data[:, 2].std()
print(f"Standard Deviation of Max Humidity: {std_max_humidity}")
std_min_humidity = home_data[:, 2].std()
print(f"Standard Deviation of Min Humidity: {std_min_humidity}")
std_max_pressure = home_data[:, 3].std()
print(f"Standard Deviation of Max Pressure: {std_max_pressure}")
std_min_pressure = home_data[:, 3].std()
print(f"Standard Deviation of Min Pressure: {std_min_pressure}")

Standard Deviation of Average Temperature: 5.0606891034780315
Standard Deviation of Average Humidity: 14.7973247859727
Standard Deviation of Average Pressure: 9.961401887249144
Standard Deviation of Max Temperature: 5.0606891034780315
Standard Deviation of Min Temperature: 5.0606891034780315
Standard Deviation of Max Humidity: 14.7973247859727
Standard Deviation of Min Humidity: 14.7973247859727
Standard Deviation of Max Pressure: 9.961401887249144
Standard Deviation of Min Pressure: 9.961401887249144


## 3.

In [71]:
count = 1
for i in range(0, 1440, 60):
    avg_60_min_temperature = home_data[i:i+60, 1].mean()
    avg_60_min_humidity = home_data[i:i+60, 2].mean()
    avg_60_min_pressure = home_data[i:i+60, 3].mean()
    print(f"Average for {count} hour(s): Temperature: {avg_60_min_temperature}, Humidity: {avg_60_min_humidity}, Pressure: {avg_60_min_pressure}")
    count += 1

Average for 1 hour(s): Temperature: 21.69875874879905, Humidity: 54.575814257940465, Pressure: 1012.5464985460106
Average for 2 hour(s): Temperature: 21.583052640022256, Humidity: 52.915691386346275, Pressure: 1010.9348956709651
Average for 3 hour(s): Temperature: 21.444763599894763, Humidity: 58.42667648372844, Pressure: 1010.8897797280962
Average for 4 hour(s): Temperature: 21.606316519749132, Humidity: 53.62837474109976, Pressure: 1009.8155847726215
Average for 5 hour(s): Temperature: 23.992994906573248, Humidity: 54.16574342998981, Pressure: 1012.7904243133045
Average for 6 hour(s): Temperature: 21.911623085111227, Humidity: 54.2096062114254, Pressure: 1012.938248456656
Average for 7 hour(s): Temperature: 20.511860959563275, Humidity: 51.81684785301697, Pressure: 1010.7823813506456
Average for 8 hour(s): Temperature: 21.37510301429885, Humidity: 52.81854227909109, Pressure: 1011.0219249200824
Average for 9 hour(s): Temperature: 22.762108066939383, Humidity: 57.2713500833662, Pressu

## 4.

In [72]:
for i in range(0, 1440):
    if home_data[i, 1] > 25:
        print(f"High Temperature Alert at {home_data[i, 0]} minutes: {home_data[i, 1]}°C")

High Temperature Alert at 0.0 minutes: 27.448178730457997°C
High Temperature Alert at 1.0 minutes: 28.790616162850387°C
High Temperature Alert at 6.0 minutes: 25.9184145172625°C
High Temperature Alert at 7.0 minutes: 29.215492872596933°C
High Temperature Alert at 8.0 minutes: 25.498710666399088°C
High Temperature Alert at 13.0 minutes: 26.47840750746672°C
High Temperature Alert at 18.0 minutes: 26.287141653869035°C
High Temperature Alert at 24.0 minutes: 25.035676620153488°C
High Temperature Alert at 25.0 minutes: 30.400501629024262°C
High Temperature Alert at 27.0 minutes: 28.28095015622183°C
High Temperature Alert at 32.0 minutes: 28.48981543891554°C
High Temperature Alert at 33.0 minutes: 27.68106210254509°C
High Temperature Alert at 42.0 minutes: 30.544123490614837°C
High Temperature Alert at 43.0 minutes: 27.517860518741884°C
High Temperature Alert at 46.0 minutes: 31.07283559398612°C
High Temperature Alert at 57.0 minutes: 25.54968050480125°C
High Temperature Alert at 59.0 minute

In [73]:
for i in range(0, 1440):
    if home_data[i, 1] == min_temperature:
        print(f"Minimum tempurature occured at {home_data[i, 0]} minutes")

Minimum tempurature occured at 137.0 minutes


## 5.

In [ ]:
np.savetxt('home_data.csv', home_data, delimiter=',')